version: "3.9"

services:
  backend:
    build: ./Backend
    ports:
      - "8080:8080"
    hostname: "backend"
    depends_on:
      service-db:
        condition: service_healthy
  service-db:
    image: postgres:14.7-alpine
    environment:
      POSTGRES_USER: echobot
      POSTGRES_PASSWORD: echobot
    ports:
      - "5432:5432"
    volumes:
      - ./Backend/infrastructure/db/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "--quiet" ]
      interval: 1s
      timeout: 5s
      retries: 10
  bot:
    build: ./Bot
    ports:
      - "8081:8081"
    hostname: "bot"
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - BOT_DELAY=${BOT_DELAY}
