ktor:
  deployment:
    host: "0.0.0.0"
    port: "8081"
  application:
    modules:
      - com.example.config.ApplicationModulesKt.koin
      - com.example.config.ApplicationModulesKt.serialization
      - com.example.config.ApplicationModulesKt.exceptions
      - com.example.config.ApplicationModulesKt.controller
      - com.example.config.ApplicationModulesKt.bot

bot:
  token: $BOT_TOKEN
  delay: $BOT_DELAY

backend:
  url: "http://backend:8080"
